# Setup virtual machine
language: node_js
node_js:
  - "lts/*"
install:
  - npm ci

# Test with code coverage
# then send results to remote
script: npm run test:cover
after_script: cat ./coverage/lcov.info | coveralls

# Deploy documentation on gh-pages
before_deploy: npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  on:
    branch: master
